# Basil's identity; how he knows a message is directed to him in group
# chats. Messages must be prefixed using "@me ", "me, " or similar.
me: basil

# Cli or Skype?
server_type: :cli

# Should dispatch messages as simple strings or enable extended readline
# support (pipelines and substitutions)?
dispatcher_type: :simple

# The directory from which plugins are loaded.
plugins_directory: ./plugins

# Where basil will persist data. Created on-demand.
pstore_file: ./basil.pstore

# Required only on OSX and ruby 1.9 for https requests to work (JIRA).
# Install curl-ca-bundle via ports. The get_* utilities will use this
# cert file for secure requests if the configuration option is present.
#https_cert_file: /opt/local/share/curl/curl-ca-bundle.crt

#########################################################################
# Additional configuration specific to plugins.
#########################################################################

jenkins:
  host:     jenkins1.example.com
  port:     80
  user:     X
  password: X

jira:
  host:     jira.example.com
  port:     443
  user:     X
  password: X

confluence:
  host:     confluence.example.com
  port:     443
  user:     X
  password: X

airbrake:
  account: ideeli
  project: SomeNumber   # https://ideeli.airbrakeapp.com/<project>/errors
  token:   SomeLongHash # get from Settings

email:
  interval: 30 # seconds
  server:   imap.gmail.com
  port:     993
  username: X
  password: X
  inbox:    INBOX

twitter:
  consumer_key:       xxx
  consumer_secret:    xxx
  oauth_token:        xxx
  oauth_token_secret: xxx
