# Bob's identity; how he knows a message is directed to him in group
# chats. Messages must be prefixed using "@me ", "me, " or similar.
me: bob

# Cli or Skype?
server_type: :cli

# Simple or Extended?
dispatcher_type: :simple

# The directory from which plugins are loaded.
plugins_directory: ./plugins

# Where bob will persist his data.
pstore_file: ./hardworkingbob.pstore

# Where a locking server will store its lock file.
lock_file: /tmp/hardworkingbob.lock
